[build]
  command = "npm run build"
  publish = "out"
  environment = {
    ADMIN_EMAIL = "",
    ADMIN_PASSWORD = "",
    ADMIN_USERNAME = "",
    NEXTAUTH_SECRET = "",
    NEXT_PUBLIC_ADMIN_KEY = "",
    NEXT_PUBLIC_ADMIN_TOKEN = "",
    UPLOAD_PATH = "",
    NEXT_TELEMETRY_DISABLED = "1"
  }

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
