[build]
  command = "npm install --legacy-peer-deps && npx prisma generate && next build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [
    "prisma/**",
    "prisma/schema.prisma"
  ]
  node_bundler = "esbuild"
