[build]
  command = "npm run build"
  publish = ".next" # The new build output directory for Next.js

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
