[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  ADMIN_EMAIL = ""
  ADMIN_PASSWORD = ""
  ADMIN_USERNAME = ""
  NEXTAUTH_SECRET = ""
  NEXT_PUBLIC_ADMIN_KEY = ""
  NEXT_PUBLIC_ADMIN_TOKEN = ""
  UPLOAD_PATH = ""
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_CACHE_DIR = ".next/cache"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-cache-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
