[build]
  command = "npx prisma generate && CI=true next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"  # Using a more recent Node.js version
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NPM_FLAGS = "--legacy-peer-deps --no-audit"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [
    "prisma/**",
    "prisma/schema.prisma"
  ]
  node_bundler = "esbuild"
