name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install & Build
        run: |
          npm ci
          npm run build && next export

      - name: Decode Firebase Admin Credentials (Base64)
        env:
          FIREBASE_ADMIN_CREDENTIALS: ${{ secrets.FIREBASE_ADMIN_CREDENTIALS }}
        run: |
          echo "${FIREBASE_ADMIN_CREDENTIALS}" | base64 --decode > firebase-admin-key.json

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: firebase-admin-key.json
          projectId: shubham-tours

      - name: Cleanup Firebase Admin Key
        run: rm firebase-admin-key.json
